### ISSUE TITLE
Utility doesnt work in Windows due to a bug in StringUtils.java

### ISSUE THREAD

**Issue by shamanthv6289** [apigee/wsdl2apigee#26]
Hi,
     I see the below error when i try to run the utility. The issue seems to be due to line 39 in **StringUtils.java** which expects "/" instead of "\" on windows machines. 
![wsdl2apigee_bug](https://user-images.githubusercontent.com/33671015/71964119-3882dd80-31ba-11ea-9c2b-a8287e9d4e69.jpg)

Jan 08, 2020 1:54:40 AM com.apigee.proxywriter.GenerateProxy prepareTargetFolder
INFO: Target proxy folder setup complete
Jan 08, 2020 1:54:40 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Read operations map
Jan 08, 2020 1:54:41 AM com.apigee.proxywriter.GenerateProxy begin
SEVERE: String index out of range: -1
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at com.apigee.utils.StringUtils.proxyNameAndBasePath(StringUtils.java:41)
        at com.apigee.proxywriter.GenerateProxy.getWSDLDetails(GenerateProxy.java:2318)
        at com.apigee.proxywriter.GenerateProxy.begin(GenerateProxy.java:2796)
        at com.apigee.proxywriter.GenerateProxy.main(GenerateProxy.java:3103)

**Comment by manucr619** [comment]
Any update on this ?
